### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by bilint01** [iamkun/dayjs#481] opened 2019-02-06 17:08 UTC
Hello,
can I ask you, if is issue on my side or on yours? 
ModuleNotFoundError: Module not found: Error: Can't resolve 'dayjs/plugin/advancedFormat'

**Comment by rodmax** [comment] 2019-02-06 19:53
i have the same issue when usu TypeScript

**Comment by iamkun** [comment] 2019-02-07 13:53
Try hotfix v1.8.5, contains module entry point fix, not sure if it related with this issue, hope it will help.

**Comment by hajimurtaza** [comment] 2019-02-07 19:45
> i have the same issue when usu TypeScript

How are you trying to load it?

**Comment by pret-a-porter** [comment] 2019-02-08 13:24
I fixed it buy
```
//@ts-ignore
import dayjs from 'dayjs';
```

**Comment by zleight1** [comment] 2019-02-10 07:23
I'm also seeing this, coming from eslint-plugin-import looking for something not found:
'..node_modules\dayjs\node_modules\@vue\cli-service\webpack.config.js'

**Comment by iamkun** [comment] 2019-02-11 06:20
@bilint01  @rodmax need more information, or a test repo that we could reproduce this issue.

**Comment by iamkun** [comment] 2019-03-14 08:26
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by iamkun** 2019-03-14 08:26 UTC
