### ISSUE TITLE
Memory leak in locales

### ISSUE THREAD

**Issue by harrysarson** [iamkun/dayjs#154] opened 2018-05-16 13:25 UTC
This was introduced in #123 and spotted first by @Frondor in https://github.com/xx45/dayjs/pull/123#issuecomment-387707910.

Here is a http://sscce.org/:

```js
const { en } = dayjs;

let i = 0;

setInterval(() => {
  document.getElementById('op').textContent = `properties added = ${i}`;

  for (let j = 0; j < 1000; ++j) {
    dayjs.locale(i.toString(), en);
    ++i;
  }
}, 0);
```

If you run this in the browser you can see that the size of the `Ls` object in dayjs grows everytime a new locale is added. I can't think of an easy fix for this.

https://repl.it/@HarrySarson/dayjs-memory-leak

**Comment by Frondor** [comment] 2018-05-16 14:30
Thanks for reproducing that, I can see how RAM is incremented by ~20 MB/s by running it.
I wasn't sure on the how, but something about that global wasn't right. Now I notice it is [directly assigned](https://github.com/xx45/dayjs/blob/cd4396e69302a0d310619ea6e63f7f8f2dac3ae0/src/index.js#L436) to the instance, again.
My initial proposal was totally re-worked with a lot of code that (in my humble opinion) added unnecessary complexity. I can no longer understand most of that approach so, I can't help here I'm afraid.

**Comment by iamkun** [comment] 2018-05-16 15:14
Thanks @harrysarson  @Frondor. 

How can I see the size of the `Ls` object?  Just check my physic memory or via chrome developer tool?

**Comment by harrysarson** [comment] 2018-05-16 19:15
I used the dev tool, just add a break point in `locale` and inspect the `Ls` object, it should have many properties.

**Comment by prantlf** [comment] 2018-09-13 05:52
I wonder, why you call this a memory leak. You deliberately register batches of 1000 locales endlessly in Day.js. Registering a locale globally is a legitimate feature, that each module can use that locale. What causes the leak is how you misuse the feature.

If your page needs to work in 1000000 locales, it is as it is and you should accept the memory growth. But if you want to show, how you can fill the memory by useless objects, you do not need Day.js for it. You can store the objects with unique keys to `window.junk` and the effect will be the same :-)

A memory leak means repeating the same piece of code a lot of times and observing memory growth in the browser. Your test code does not qualify as a memory leak demonstration, because by `++i` and `i.toString()` you do not  repeat the same locale registration. At least not as a memory lean *in Day.js*.

**Comment by iamkun** [comment] 2019-02-02 08:59
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by iamkun** 2019-02-02 08:59 UTC
