### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by lingxuesonga** [iamkun/dayjs#948] opened 2020-07-01 06:43 UTC
**Describe the bug**
Typescript
TypeError: Cannot read property '1' of undefined

**Comment by iamkun** [comment] 2020-07-01 06:51
Any demo code, please?

**Comment by Balvajs** [comment] 2020-07-06 09:42
Happens to me as well. It's caused by `.format()`.
If I try `dayjs().format()` it throws `Cannot read property '6' of undefined`. Today is the 6th of July, so it seems that it cannot read a map of days.
Version `1.8.28`

**Comment by iamkun** [comment] 2020-07-06 09:53
@Balvajs can you please paste your code to https://runkit.com/embed/fjo8wb8pkq4v

**Comment by Balvajs** [comment] 2020-07-06 10:42
Turns out we do this in our app
```
    dayjs.locale({
      name: language,
      weekStart: getWeekStartByLocale(language),
      formats: {},
      relativeTime: {},
    })
```
which sets `locale.months` to `undefined`, which causes error in format function every time.
It's kinda unintuitive, because calling for example `dayjs().format('MM/YY')` shouldn't need localized months.

**Comment by iamkun** [comment] 2020-07-06 10:58
dayjs will process `locale.months` at the beginning of the `format` function even if no 'MMMM' format string is used.

**Comment by iamkun** [comment] 2020-10-27 07:31
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by iamkun** 2020-10-27 07:31 UTC

**Comment by SaiRS** [comment] 2021-06-17 09:11
```
import dayjs from "dayjs";
import "dayjs/locale/zh-cn";

dayjs.locale("zh-cn", {
// if I set this
  weekStart: 1
});

console.log(dayjs().format());
```

If I set `weekStart: 1`，then the error comes.

![image](https://user-images.githubusercontent.com/10457315/122367522-1684b180-cf8f-11eb-8405-87ea7567faab.png)

**Comment by ws-hofshteyn** [comment] 2021-08-29 11:05
Got the same issue. Working with React + Typescript:
```
import React from 'react';
import dayjs from 'dayjs';
import weekday from 'dayjs/plugin/weekday';
import 'dayjs/locale/ru';

dayjs.extend(weekday);

dayjs.locale('ru', {
    weekStart: 1
});

export const DateFromatter = () => {
    return <div>{dayjs().format()}</div>;
}
```

**Comment by adrianiy** [comment] 2021-10-01 22:27
I'm facing the same issue trying to modify `L` format to be `YYYY-MM-DD`, is there another way to create a shorthand to this format?

latest try was this

```js
const localeOptions = {
    name: 'es',
    formats: {
        L: 'YYYY-MM-DD'
    }
};
dayjs.locale('es-custom', localeOptions);
```

**Comment by adrianiy** [comment] 2021-10-01 22:32
Just made it work, maybe a bit "tricky" way but it works:
```js
import esLocale from 'dayjs/locale/es';

const localeOptions = {
    ...esLocale,
    formats: {
        ...esLocale.formats,
        L: 'YYYY-MM-DD'
    }
};
dayjs.locale('es-custom', localeOptions);
```
