### ISSUE TITLE
Updating locale does not use a default future/past suffix

### ISSUE THREAD

**Issue by Bonfire** [iamkun/dayjs#1248] opened 2020-12-03 23:54 UTC
**Describe the bug**
If a user specifies a custom `relativeTime` config, DayJS does not set `future` or `past` to their default values. As a result, if the user does not define `future` or `past`, DayJS will throw an error when calling `dayjs().fromNow()`.

If the user specifies not to use a suffix (by doing `dayjs().fromNow(true);`) the issue does not occur.

**Expected behavior**
If the user updates a locale (using `dayjs.updateLocale()`), and specifies a custom `relativeTime` but does not include `future` or `past`, DayJS should use their default values.

I do not know if this issue exists for all fields in `relativeTime` (such as `s`, `ss`, etc.).

**Information**
 - Day.js Version: 1.9.6
 - OS: Windows
 - Browser: N/A (Node.js v14.15.1)
 - Time zone:  Eastern Standard Time

**Reproduction**
```js
var dayjs = require("dayjs")
var relativeTime = require('dayjs/plugin/relativeTime')
var updateLocale = require('dayjs/plugin/updateLocale')

dayjs.extend(relativeTime);
dayjs.extend(updateLocale);

dayjs.updateLocale('en', {
    relativeTime: {
        s: '%d second',
        ss: '%d seconds',
        m: '%d minute',
        mm: '%d minutes',
        h: '%d hour',
        hh: '%d hours',
        d: '%d day',
        dd: '%d days',
        M: '%d month',
        MM: '%d months',
        y: '%d year',
        yy: '%d years'
    }
});

dayjs().fromNow();
```
Which results in the following error:
```
TypeError: Cannot read property 'replace' of undefined
```

I believe the issue specifically lies here: https://github.com/iamkun/dayjs/blob/eb5fbc4c7d1b62a8615d2f263b404a9515d8e15c/src/plugin/relativeTime/index.js#L67

**Comment by iamkun** [comment] 2020-12-04 02:23
there should be a fix in UpdateLocale Plugin to merge the updated object
Duplicate of #1118

**Closed by iamkun** 2020-12-04 02:23 UTC
