### ISSUE TITLE
Issue formatting 02/20

### ISSUE THREAD

**Issue by mason-terry** [iamkun/dayjs#711] opened 2019-10-30 21:03 UTC
**Describe the bug**
``` const month = dayjs.utc(02/20, 'MM/YY').format('MM')```
```const year = dayjs.utc(02/20, 'MM/YY').format('YYYY')```

The above returns:

```month = 03```
```year = 2020```

**Expected behavior**
```month = 02```
```year = 2020```

**Additional Information**
I think this is a leap year issue

**Information**
 - Day.js Version: v1.8.16
 - OS: MacOS 10.14
 - Browser Chrome 78
 - Time zone: GMT-06:00 DST (Central Daylight Time)

**Comment by iamkun** [comment] 2019-10-31 17:02
https://runkit.com/embed/ydhiaf56iwjl

<img width="560" alt="Screen Shot 2019-11-01 at 1 02 14 AM" src="https://user-images.githubusercontent.com/17680888/67969010-558fb300-fc43-11e9-8058-9c89d96d425f.png">


please provide a valid reproduction link

**Comment by marc-fisher-q2e** [comment] 2019-10-31 18:58
Odd, just cloning that example I see a different result, no changes.

https://runkit.com/svjard/5dbb2da38795ea001414b056

**Comment by mason-terry** [comment] 2019-10-31 19:01
I got the same results as ☝️

**Comment by iamkun** [comment] 2019-11-01 04:12
This is because if no 'day' provided, dayjs will use current 'day'. But we might change it to the first day of month

**Comment by iamkun** [comment] 2020-01-06 09:09
fixed in #761 and will use the first day of the month while there's no 'day' provided.

**Closed by iamkun** 2020-01-06 09:09 UTC
