### ISSUE TITLE
Plugins: how extend only one instance of dayjs?

### ISSUE THREAD

**Issue by gpbl** [iamkun/dayjs#655] opened 2019-08-11 10:44 UTC
I'm evaluating this library for [react-day-picker](http://react-day-picker.js.org) and I have a concern about plugins. 

For what I understand, extending dayjs with plugins will affect all the instances of dayjs. 

E.g. if I extend dayjs with `weekOfYear` plugin, the dayjs instances used by an application implementing react-day-picker+dayjs will be extended too. Is it correct? If yes, how to extend just one instance of dayjs?

**Comment by iamkun** [comment] 2019-08-11 11:55
Yes, and I can’t see if there is a problem. What’s your concern, please?

**Comment by gpbl** [comment] 2019-08-13 12:28
Thanks @iamkun for your answer,

I don't agree much with this design choice. Not that I expect it giving practical problems for now, but an external component using dayjs would alter how dayjs works in the whole app. This doesn't sound correct to me. What I would have preferred is a factory like:

```js
const dayjs = dayjs.factory();
dayjs.extend(aPlugin); // only this instance of dayjs will use `aPlugin`
```

Just my feedback! Thanks for your work on dayjs!

**Comment by iamkun** [comment] 2019-08-13 12:33
Thanks.  To keep only one type of dayjs might be better I think. 😊

**Comment by iamkun** [comment] 2019-08-26 03:43
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by iamkun** 2019-08-26 03:43 UTC

**Comment by szympajka** [comment] 2020-10-13 12:10
@iamkun, I found this issue as I was actually looking for the sort of `factory` function. 

The problem I have is this:

```js
dayjs.extend(updateLocale);

dayjs.updateLocale('en', {
  relativeTime: {
    future: 'in %s',
    past: '%s ago',
    s: '<1 min',
    m: '1 min',
    mm: '%d mins',
    h: '1 hour',
    hh: '%d hours',
  },
});
```

So I updated locales according to our product needs, but now it will update it for the entire app which I believe is not what we want.

What can be a work around here?

**Comment by iamkun** [comment] 2020-10-14 01:54
@szympajka there's no dayjs factory function atm.

In your case, it's better to use two locales.

e.g.

```js
import somelocale from 'dayjs/locale/somelocale'

// update somelocale to other config and name
const otherlocale = {
  name: 'otherlocale',
   ...somelocale
}

// then register otherlocale
dayjs().locale(otherlocale)

// then you will have two locale config that you want

dayjs().locale(somelocale)
dayjs().locale(otherlocale)
```

**Comment by szympajka** [comment] 2020-10-14 09:11
thanks, @iamkun, it helped :)

**Comment by kb-ally** [comment] 2021-11-10 18:14
I need to have badMutable plugin in specific places not globally , any suggestions @iamkun

**Comment by marnixhoh** [comment] 2022-08-23 08:07
@kb-ally I have the same issue. How did you end up solving it?

**Comment by marnixhoh** [comment] 2022-08-23 08:31
For anyone struggling with the same, I found a solution.

I imported dayjs twice, one which is mutable and one which isn't by adding a query param to the import:

```
import dayjs from 'dayjs';
import dayjsMutable from 'dayjs?mutable';
```

**Comment by gjc9620** [comment] 2022-09-16 10:44
How to change local to UTC time?
like 
```
dayjs().locale(UTC)?
```

**Comment by Krebsy** [comment] 2022-10-11 20:09
> @szympajka there's no dayjs factory function atm.
> 
> In your case, it's better to use two locales.
> 
> e.g.
> 
> ```js
> import somelocale from 'dayjs/locale/somelocale'
> 
> // update somelocale to other config and name
> const otherlocale = {
>   name: 'otherlocale',
>    ...somelocale
> }
> 
> // then register otherlocale
> dayjs().locale(otherlocale)
> 
> // then you will have two locale config that you want
> 
> dayjs().locale(somelocale)
> dayjs().locale(otherlocale)
> ```

This doesn't work if you need to use both concurrently.

**Comment by Slapbox** [comment] 2022-11-18 23:56
This should really be re-opened. This is the same sort of unexpected behavior that people are leaving `moment` to get away from.

**Comment by adguy360** [comment] 2023-04-09 14:28
Hi @iamkun,

In a micro frontend architecture with a single appshell hosting multiple (full app) remotes, each remote should be able to set its own default day js configs (locale, tz ec) without affecting/overriding other remotes.
This is a common scenario with a relatively simple MF architecture, how does day js support such cases with a global singleton?

**Comment by Ecksters** [comment] 2023-05-02 23:25
Seems like you could keep the current behavior as the default, but offer a method that returns a new untouched DayJS instance, for cases like this.

**Comment by Slapbox** [comment] 2023-05-03 00:06
@iamkun would you be open to reconsidering your previous stance? I think many developers would prefer to use `dayjs` instead of `moment` but this remains a blocker for us and surely others.

**Comment by rubennaatje** [comment] 2023-06-03 14:38
> ```js
> const dayjs = dayjs.factory();
> ```

For me it's an issue when using it as a replacement for moment.js in a 3rd party library.

In the rest of my codebase i do want to use the non BadMutable version of Dayjs.

**Comment by switz** [comment] 2023-07-17 20:14
yeah would prefer plugins/updateLocale to return an immutable instance of dayjs rather than overriding global config

**Comment by beefchimi** [comment] 2023-09-11 21:06
@iamkun the code you shared with @szympajka does not appear to work... I am unable to have a custom `locale` for just one component. Example here: https://codesandbox.io/s/dayjs-testing-rr26qy

That being said, I am in agreeance with other commenters in this thread - it would be ideal to spawn a unique instance of `dayjs` so that we can `extend` it without affecting any other instance.

**Comment by Slapbox** [comment] 2023-12-12 22:56
I think this package is unmaintained, but still, friendly bump.

**Comment by dhiwakar-aidora** [comment] 2024-08-01 03:48
Gentle bump here.

I have a use-case for this too (as documented on issue https://github.com/iamkun/dayjs/issues/2702). Has anyone figured a workaround for this?

**Comment by Nantris** [comment] 2024-08-01 21:00
@iamkun I was under the impression this library was unmaintained due to this issue being ignored, but I see there was a recent release.

Would you be willing to open this issue? Whether you plan to address it or not, opening it at least signals willingness to address this if the community does the legwork.

**Comment by macrozone** [comment] 2024-10-11 09:53
dayjs beeing a singleton in regards to plugin is surprising and can lead to unexpected errors, since the behavior and api of dayjs now behaves on whether certain plugins have been imported somewhere.

It makes dayjs unpredictable in terms of plugins. You may accidentially load plugins that you did not want and increase bundle size, or you may rely on a plugin accidentially that is imported somewhere else, but after a refactor it no longer works. Even worse if a plugin would change the default behaviour of dayjs.

I suggest to introduce a factory method like described and make sure that the global dayjs is unaltered when attaching plugins to the factory return value.

also i'd suggest to deprecate the existing behavior because it is so dangerous

**Comment by Nantris** [comment] 2024-10-11 20:25
I _really_ wish this would at least be re-opened... I never moved on from Moment, because how is this better? At least Moment was unpredictable because of mutability, but DayJS is unpredictable because of something much closer to "magic" and magic is always worse.

**Comment by thelinuxlich** [comment] 2024-12-26 21:41
What would be the solution for this?

**Comment by mcdado** [comment] 2025-01-25 23:16
> What would be the solution for this?

A named export for the `Dayjs` class, in my opinion.

https://github.com/iamkun/dayjs/blob/3738cc1db0d855e68b65ec775a38898c02586b76/src/index.js#L85

**Comment by Nantris** [comment] 2025-01-26 03:36
I took a very quick and lazy shot at forking the package to address this but I haven't had any chance to give it a try yet.

In theory it should be backwards compatible with the original dayjs (if it works at all, that is.)

**Feel free to give it a try:** https://github.com/Nantris/dayjs

https://github.com/Nantris/dayjs/blob/96a46b594c3cc0751d64703896934a9e07687c43/src/index.js#L698-L701

**Comment by denvudd** [comment] 2025-03-18 14:58
Does anyone found the solution for it? I stuggle with `updateLocale` setup

**Comment by Nantris** [comment] 2025-03-18 22:32
@denvudd you could try the fork (of unknown quality) I linked above? Otherwise, no, there is no solution.

**Comment by Nantris** [comment] 2025-04-17 00:28
This can never work without a lot of work because DayJS's existing plugins modify the prototypes directly. You're probably just better off waiting for https://caniuse.com/temporal
