### ISSUE TITLE
UTC Plugin - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by MartijnHarmenzon** [iamkun/dayjs#813] opened 2020-03-03 09:28 UTC
**Describe the bug**
I am trying to include the utc plugin within a Vanilla JS project like this:
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.8.21/dayjs.min.js"></script>
  <script src="./dayjs-utc.js"></script>

  <script>
    dayjs.extend(window.utc);
  </script>
```

I saved the content of the utc plugin within the dayjs-utc.js file.

This results in the following error:
**SyntaxError: Cannot use import statement outside a module**

**Expected behavior**
Could someone help me to include the utc plugin within a Vanilla JS project? 

**Information**
 - Day.js Version [v1.8.21]
 - OS: [Windows 10]
 - Browser [Chrome]
 - Time zone: [Amsterdam]

**Comment by iamkun** [comment] 2020-03-03 09:35
Duplicate of #812

**Closed by iamkun** 2020-03-03 09:35 UTC

**Comment by MartijnHarmenzon** [comment] 2020-03-03 09:42
Thanks for the quick response @iamkun. The answer can ideed be found here #812.
