### ISSUE TITLE
parse不支持Q quarter吗？

### ISSUE THREAD

**Issue by PengJiyuan** [iamkun/dayjs#1028] opened 2020-08-27 16:04 UTC
dayjs('2020-Q1', `YYYY-\QQ`) 这样。

@iamkun

**Comment by iamkun** [comment] 2020-08-28 03:02
will add this soon

**Comment by iamkun** [comment] 2020-09-12 09:16
Duplicate of #845

**Closed by iamkun** 2020-09-12 09:16 UTC

**Comment by leehaoChen** [comment] 2022-05-25 08:10
Hasn't it been fixed yet? I tried and it still doesn't work
