### ISSUE TITLE
TypeScript error in dayjs/index.d.ts(20,29)：Type expected.  TS1110

### ISSUE THREAD

**Issue by virzs** [iamkun/dayjs#1301] opened 2021-01-03 10:13 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/44538687/103476256-16349780-4def-11eb-8a53-39552b2aeb37.png)

**Information**
 - Day.js Version [e.g. v1.10.0]
 - Typescript Version [v3.7.2]

**Comment by iamkun** [comment] 2021-01-03 10:32
Duplicate of #1300

**Closed by iamkun** 2021-01-03 10:32 UTC
