### ISSUE TITLE
Cannot find name 'unknown'

### ISSUE THREAD

**Issue by torrescristian** [iamkun/dayjs#904] opened 2020-05-12 18:49 UTC
**Describe the bug**

ERROR in node_modules/dayjs/index.d.ts(99,30): error TS2304: Cannot find name 'unknown'.
node_modules/dayjs/index.d.ts(101,30): error TS2304: Cannot find name 'unknown'.

**Information**
 - Day.js Version 1.8.26
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Brave 1.8.95 Chromium: 81.0.4044.138
 - Time zone: GMT-03:00
 - Angular: 6.1.0
 - Typescript: 2.7.2 

I see it is caused by TypeScript version ("unknown" is > TS 3.x) what can I do?

**Comment by iamkun** [comment] 2020-05-13 02:20
a reproduction repo, please?

**Comment by iamkun** [comment] 2020-05-28 09:02
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by iamkun** 2020-05-28 09:02 UTC
