### ISSUE TITLE
Unable to parse date in russian format

### ISSUE THREAD

**Issue by akaSybe** [iamkun/dayjs#898] opened 2020-05-10 15:05 UTC
**Describe the bug**

Dayjs can't parse date in russian format

https://codesandbox.io/s/dayjs-parse-russian-date-error-wv2wh

**Expected behavior**

Should correctly parse date and return valid dayjs object. Moment.js works correctly

**Information**
 - Day.js Version: 1.8.26
 - OS: MacOS
 - Browser: 81.0.4044.138
 - Time zone: Moscow

**Comment by iamkun** [comment] 2020-05-10 15:15
Please check as a reference. https://day.js.org/docs/en/parse/string-format

**Comment by iamkun** [comment] 2020-05-11 03:05
Hi, is '08 мая 2020' , '08 май 2020' both valid string in `ru`? 

This bug is caused by two different month strings. https://github.com/iamkun/dayjs/blob/dev/src/locale/ru.js#L4

**Comment by akaSybe** [comment] 2020-05-11 11:18
'май' is a nominative case and 'мая' is a genitive case.

'08 мая 2020' is the most common date form as I know.

But anyway, looks like dayjs right now doesn't parse both '08 мая 2020' and '08 май 2020'

I could help you with PR

**Comment by iamkun** [comment] 2020-05-14 07:40
Fixed in #908

**Closed by iamkun** 2020-05-14 07:40 UTC
Labels: ☢️Bug
